---
title: "Untitled"
author: "Job Knoester"
date: "16 juin 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(include = TRUE)

library(corrplot)
library(ggplot2)
library(plotly)
library(GGally)
library(ade4)
library(mice)
library(reshape2)
library(FD)
library(gridExtra)
library(explor)
library(picante)
library(parallel)
library(hypervolume)
library(moments)
library(cati)
library(ggdendro)
library(doBy)
library(BayesFactor)
```



## Diversity indices with sampling point as communities
```{r}
abunmatsalSPR <- dcast(prosal, interaction(Plot,SamplingPoint.Replicate)~Specimen, length)
row.names(abunmatsalSPR) <- abunmatsalSPR[,1]
abunmatsalSPR <- abunmatsalSPR[,2:dim(abunmatsalSPR)[2]] 

dbFDsalSPR <- dbFD(x = promatsal, a = abunmatsalSPR, w.abun = FALSE, stand.x = TRUE, ord = c("podani", "metric"), asym.bin = NULL, calc.FRic = TRUE, m = 6, stand.FRic = FALSE, scale.RaoQ = FALSE, calc.FGR = FALSE, clust.type = "ward", km.inf.gr = 2, km.sup.gr = nrow(x) - 1, km.iter = 100, km.crit = c("calinski", "ssi"), calc.CWM = TRUE, CWM.type = c("dom", "all"), calc.FDiv = TRUE, dist.bin = 2, print.pco = FALSE, messages = TRUE)

FDsalSPR <- as.data.frame(cbind(dbFDsalSPR$FRic,dbFDsalSPR$FEve,dbFDsalSPR$FDiv,dbFDsalSPR$FDis))
colnames(FDsalSPR) <- c("FRicsal","FEvesal","FDivsal","FDissal")


abunmatnotsalSPR <- dcast(pronotsal, interaction(Plot,SamplingPoint.Replicate)~Specimen, length)
row.names(abunmatnotsalSPR) <- abunmatnotsalSPR[,1]
abunmatnotsalSPR <- abunmatnotsalSPR[,2:dim(abunmatnotsalSPR)[2]] 

dbFDnotsalSPR <- dbFD(x = promatnotsal, a = abunmatnotsalSPR, w.abun = FALSE, stand.x = TRUE, ord = c("podani", "metric"), asym.bin = NULL, calc.FRic = TRUE, m = 6, stand.FRic = FALSE, scale.RaoQ = FALSE, calc.FGR = FALSE, clust.type = "ward", km.inf.gr = 2, km.sup.gr = nrow(x) - 1, km.iter = 100, km.crit = c("calinski", "ssi"), calc.CWM = TRUE, CWM.type = c("dom", "all"), calc.FDiv = TRUE, dist.bin = 2, print.pco = FALSE, messages = TRUE)

FDnotsalSPR <- as.data.frame(cbind(dbFDnotsalSPR$FRic,dbFDnotsalSPR$FEve,dbFDnotsalSPR$FDiv,dbFDnotsalSPR$FDis))
colnames(FDnotsalSPR) <- c("FRicnotsal","FEvenotsal","FDivnotsal","FDisnotsal")

proant$PlotSamplingPoint <- interaction(proant$Plot,proant$SamplingPoint)
abunmatantSPR <-summaryBy(data = proant, formula = Abundance ~ Gen_sp+PlotSamplingPoint, FUN = sum, keep.names = T, na.rm = T)
abunmatantSPR <- dcast(abunmatantSPR, PlotSamplingPoint~Gen_sp)
row.names(abunmatantSPR) <- abunmatantSPR[,1]
abunmatantSPR <- abunmatantSPR[,2:dim(abunmatantSPR)[2]]
abunmatantSPR[is.na(abunmatantSPR)] <- 0

dbFDantSPR <- dbFD(x = promatant, a = abunmatantSPR, w.abun = FALSE, stand.x = TRUE, ord = c("podani", "metric"), asym.bin = NULL, calc.FRic = TRUE, m = 6, stand.FRic = FALSE, scale.RaoQ = FALSE, calc.FGR = FALSE, clust.type = "ward", km.inf.gr = 2, km.sup.gr = nrow(x) - 1, km.iter = 100, km.crit = c("calinski", "ssi"), calc.CWM = TRUE, CWM.type = c("dom", "all"), calc.FDiv = TRUE, dist.bin = 2, print.pco = FALSE, messages = TRUE)

FDantSPR <- as.data.frame(cbind(dbFDantSPR$FRic,dbFDantSPR$FEve,dbFDantSPR$FDiv,dbFDantSPR$FDis))
colnames(FDantSPR) <- c("FRicant","FEveant","FDivant","FDisant")

FDSPR <- merge(FDnotsalSPR,FDantSPR, by = "row.names")
FDSPR <- merge(FDnotsalSPR, FDsalSPR, by = "row.names")


# FDPlot
```

ploting results
```{r}
l <-  ggplot() +   geom_boxplot(data = FDSPR, aes(x=Plot, y=FRic),  colour="black")
m <-  ggplot() +   geom_boxplot(data = FDSPR, aes(x=Plot, y=FEve),  colour="black")
n <-  ggplot() +   geom_boxplot(data = FDSPR, aes(x=Plot, y=FDiv),  colour="black")
o <-  ggplot() +   geom_boxplot(data = FDSPR, aes(x=Plot, y=FDis),  colour="black")
p <-  ggplot() +   geom_boxplot(data = FDSPR, aes(x=Plot, y=RaoQ),  colour="black")

grid.arrange(l,m,n,o,p, ncol=3)

pairwise.wilcox.test(FDSPR$FRic,FDSPR$Plot)
pairwise.wilcox.test(FDSPR$FEve,FDSPR$Plot)
pairwise.wilcox.test(FDSPR$FDiv,FDSPR$Plot)
pairwise.wilcox.test(FDSPR$FDis,FDSPR$Plot)
pairwise.wilcox.test(FDSPR$RaoQ,FDSPR$Plot)

# cor.test(FDPlot$FRic,FDPlot$Transect, method = "spearman")
# cor.test(FDPlot$FEve,FDPlot$Transect, method = "spearman")
# cor.test(FDPlot$FDiv,FDPlot$Transect, method = "spearman")
# cor.test(FDPlot$FDis,FDPlot$Transect, method = "spearman")
# cor.test(FDPlot$RaoQ,FDPlot$Transect, method = "spearman")

```